version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: newsmyroom_backend
    ports:
      - "5000:5000"  # Express 서버 포트
    environment:
      - MONGO_URI=mongodb://mongo:27017/newsmyroom
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - newsmyroom_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: newsmyroom_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - newsmyroom_network

  mongo:
    image: mongo:6.0
    container_name: newsmyroom_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
    networks:
      - newsmyroom_network

networks:
  newsmyroom_network:
    driver: bridge
