# newsmyroom/docker-compose.yml

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Express 서버 포트
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    networks:
      - newsmyroom_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - newsmyroom_network

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
    networks:
      - newsmyroom_network

networks:
  newsmyroom_network:
    driver: bridge
