version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - newsmyroom_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - frontend_node_modules:/usr/share/nginx/html/node_modules
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - newsmyroom_network

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
    networks:
      - newsmyroom_network

networks:
  newsmyroom_network:
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules:
